name: BADHON-update

on:
  workflow_dispatch:

jobs:
  setup-rdp-tunnel:
    runs-on: windows-2025

    steps:
    - name: Check out the-v
      uses: actions/checkout@v2

    - name: Download full-v1
      run: |
        curl -L -o code.zip https://gitlab.com/badhon2/work/-/raw/main/masum.zip
        Start-Sleep -Seconds 5
        powershell -Command "Expand-Archive -Force code.zip $env:USERPROFILE\extracted"

    - name: Download and Install Playit
      run: |
        Invoke-WebRequest -Uri "https://github.com/playit-cloud/playit-agent/releases/download/v0.15.26/playit-windows-x86_64-signed.exe" -OutFile "$env:USERPROFILE\playit.exe"
        Start-Sleep -Seconds 5

    - name: TS-v4
      run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
    - run: Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
    - run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
    - run: Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "admin@123" -Force)
    
    - name: Install Python packages
      run: |
       python -m pip install --upgrade pip
       pip install pyautogui
       pip install keyboard

    - name: varton-7896
      env:
        PLAYIT_AUTH_KEY: ${{ secrets.DF }} 
      run: |
        Start-Process -FilePath "$env:USERPROFILE\playit.exe" -ArgumentList "--secret $env:PLAYIT_AUTH_KEY" -NoNewWindow -Wait
        Start-Process -FilePath "$env:USERPROFILE\playit.exe" -NoNewWindow
        
    - name: Keep alive
      run: Start-Sleep -Seconds 21600
